# Generated by Django 3.1.5 on 2021-01-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscribed_to',
        ),
    ]
